CREATE DATABASE TEST1
GO

USE TEST1
GO

CREATE TABLE UserInfo(
	UserId INT CONSTRAINT PK_UserInfo PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	EmailAddress NVARCHAR(50) UNIQUE NOT NULL,
	PhoneNumber NUMERIC(10) CONSTRAINT CK_User_PhoneNumber UNIQUE NOT NULL,
	Password NVARCHAR(20) NOT NULL,
	IsAdmin BIT DEFAULT 0,
	Created_At DATETIME NOT NULL DEFAULT GETDATE()
);

INSERT INTO UserInfo VALUES('Ankit','Rudani','ankitrudani234@gmail.com',9974289426,'Ankit@1234',1,DEFAULT);

SELECT * FROM UserInfo