CREATE DATABASE Hospital
GO

USE Hospital
GO

CREATE TABLE Departments(
	DepartmentID INT IDENTITY(1,1) CONSTRAINT PK_Department_ID PRIMARY KEY,
	DepartmentName VARCHAR(50) NOT NULL
);

CREATE TABLE Doctors(
	DoctorID INT IDENTITY(1,1) CONSTRAINT PK_Doctor_ID PRIMARY KEY,
	DoctorName VARCHAR(30) NOT NULL,
	Phone NUMERIC(10),
	DepartmentID INT CONSTRAINT FK_Doctors_DepartmentID FOREIGN KEY REFERENCES Departments ON DELETE SET NULL
);

CREATE TABLE Assistants(
	AssistantID INT IDENTITY(1,1) CONSTRAINT PK_Assistant_ID PRIMARY KEY,
	AssistantName VARCHAR(30) NOT NULL,
	Phone NUMERIC(10),
	DepartmentID INT CONSTRAINT FK_Assistants_DepartmentID FOREIGN KEY REFERENCES Departments ON DELETE SET NULL
);

CREATE TABLE Patients(
	PatientID INT IDENTITY(1,1) CONSTRAINT PK_Patient_ID PRIMARY KEY,
	PatientName VARCHAR(30) NOT NULL,
	Age INT CONSTRAINT CK_Age_not_Negative CHECK (Age>0),
	Gender CHAR NOT NULL CONSTRAINT CK_Gender CHECK(Gender IN ('M','F','O')),
	DoctorID INT CONSTRAINT FK_Patient_DoctorID FOREIGN KEY REFERENCES Doctors ON DELETE SET NULL,
	AssistantID INT CONSTRAINT FK_Patient_AssistantID FOREIGN KEY REFERENCES Assistants ON DELETE SET NULL,
);

CREATE TABLE Drugs(
	DrugID INT IDENTITY(1,1) CONSTRAINT PK_Drug_ID PRIMARY KEY,
	DrugName VARCHAR(30) NOT NULL,
);

CREATE TABLE DrugSummary(
	ID INT IDENTITY(1,1) CONSTRAINT PK_DrugSummary_ID PRIMARY KEY,
	PatientID INT CONSTRAINT FK_DS_PatientID FOREIGN KEY REFERENCES Patients ON DELETE SET NULL,
	DrugID INT CONSTRAINT FK_DS_DrugID FOREIGN KEY REFERENCES Drugs ON DELETE SET NULL,
	Time VARCHAR(10) NOT NULL CONSTRAINT CK_Drug_time CHECK(Time IN ('Morning','Afternoon','Night'))
);
